### PR TITLE
Use latest golang versions

### PR DESCRIPTION
**Pull request by larhauga**

### CODE REVIEW

**Comment by anderseknert** [comment]
Can you rebase this and fix the conflict? That'd be a good first test of publishing the edge tag I guess :)

**Comment by anderseknert** [comment]
Screenshot 2023-11-20 at 11 20 15

**Comment by larhauga** [comment]
> Did you see that on main? I'm not sure what it's referring to tbh 🤔 Is it from the cleanup phase or just delayed to make it look like so?

I think I messed up the repo+tag part here. Something got mangeled due to the `-v2` part, but the main issue is a missing variable (TAG_NAME i think):

```
docker push foo:
invalid reference format
```

**Comment by larhauga** [comment]
I think this branch should contain the necessary changes for the workflows to work correctly

**Comment by anderseknert** [comment]
Seems to have worked! It's marked as "private" though. I'll need to look into why, and how to change it.

**Pull request merged**
