### PR TITLE
Update dependencies to latest versions

### PR DESCRIPTION
**Pull request by rendler-denis**

### CODE REVIEW

**Comment by rendler-denis** [comment]
@anderseknert I've updated the dependencies and tested it. all tests were green and I was able to reproduce successfully the tutorial in the docs.

This PR is related to:
https://github.com/open-policy-agent/opa-docker-authz/issues/63

**Comment by anderseknert** [comment]
Thanks Denis! 

Looks like you may need to run `go mod vendor` to have that updated.

You'll also need to sign-off on the commit for the DCO check, i..e:

```
git commit --amend --signoff
git push --force
```

**Comment by rendler-denis** [comment]
good morning, @anderseknert !  

done on all accounts :D thank you for the quick reply on this one :)

**Comment by anderseknert** [comment]
@rendler-denis I just pushed 0.9 with your changes included. Try it out and let me know if things work as expected :)

**Comment by rendler-denis** [comment]
I was just about to look if the new version is up. Will do and comeback with results. Thanks for the quick response.

**Comment by rendler-denis** [comment]
@anderseknert I tried installing the plugin on a x64 machine and I get an error that says:

```
 level=error msg="exec /opa-docker-authz: exec format error"
```

and when I look at the file on the disk I see this:

```
/var/lib/docker/plugins/14b8c88a919bdf3ab69f2a32e2ad070c80331bc24e3d35f39a1f200022a27cd8/rootfs/opa-docker-authz: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), statically linked, Go BuildID=W9QoemJsbI4n5Q23Hrqs/bALtCkqazVGCR5zfujOg/M0w1uj8LkETl5zYo3sET/IDFSZUdg1rOZlVX50ssm, with debug_info, not stripped
```

Am I reading this correctly, is it installing an ARM version?

**Comment by anderseknert** [comment]
Doh! 🤦 We don't have a publishing pipeline set up for this, so of course... I'll need to cross compile for Linux AMD64 and have that pushed (I'm on an M1 mac myself). I'll look into it. Sorry about that!

**Comment by rendler-denis** [comment]
@anderseknert no worries. I suspected that. I'll take a look and maybe contribute with a pipeline as well :) But first I need to learn a bit more about the plugins architecture

**Comment by anderseknert** [comment]
@rendler-denis it's hard contributing anything where credentials is involved. I might take a stab at it at some point but this plugin has been pushed infrequently enough that it's not been worth the effort up til this point at least.

I've just pushed v0.9 again, this time using GOOS=linux and GOARCH=amd64. Could you please try again to see if it works better now? At least _I_ got the exec format error when trying to run the binary now, so whatever it is it isn't Mac ARM 😄

**Comment by rendler-denis** [comment]
@anderseknert I can confirm, now it works. Thank you.

**Pull request merged**
