### PR TITLE
Update OPA version, vendor and current version

### PR DESCRIPTION
**Pull request by chronidev**
Update OPA version to 0.13.5. 
Update current version to 0.5.
glide up

### CODE REVIEW

**Comment by tsandall** [comment]
@chronidev please re-run with --strip-vendor. It looks like (at least) the OPA vendor directory is included.

**Comment by chronidev** [comment]
@tsandall done. Thanks for the review

**Comment by tsandall** [comment]
@chronidev thanks. Please squash your changes. Also, it looks like the VERSION flag in the Makefile was not updated to 0.5 like it'll need to be. If you want to do this, go ahead.

**Comment by chronidev** [comment]
It should be ok now.

**Comment by chronidev** [comment]
Thanks for the merge, do you plan to publish this release ?

**Comment by tsandall** [comment]
I just published 0.5.

**Pull request merged**
