### PR TITLE
WIP: resolve symlinked host binds

### PR DESCRIPTION
**Pull request by flixr**
Resolve symlinked host binds and provide them in `HostBinds`, so we can properly check the paths.
Should solve #34

### CODE REVIEW

**Comment by flixr** [comment]
@anderseknert I updated it a bit for my use-case so I can allow only ReadOnly bind mounts where the source already exists (so that docker doesn't create dirs that don't exist):
* BindMounts: all requested bind mounts
* BindMountsResolved: _resolved_ bind mounts (so must exist on the host) to avoid circumvention by symlink.
* BindMountsResolvedRO: additonally only contains ReadOnly mounts.

and then update the policy from above with
```
restricted_host_bind
{
    allowed_host_binds := {x | x:= input.BindMountsResolvedRO[_]; startswith(x, allowed_host_path_prefixes[_])}
    count(input.BindMounts) != count(allowed_host_binds)
}
```

**Comment by anderseknert** [comment]
Looks sensible to me @flixr ... we'd still need some tests to cover this. I've been pretty swamped recently but starting to look better from next week if you want me to help out with that.

**Comment by flixr** [comment]
@anderseknert did you have a chance to continue here yet?

**Comment by anderseknert** [comment]
I haven't @flixr ... feel free to pick it up! I don't think I'll be able to in the near future.

**Comment by flixr** [comment]
For now this does all I need right now and is running fine in production.
Also don't have time to spend on making this more complete atm...

**Pull request closed without merging**
